language: fr

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: False
    epochs: 200
  - name: ResponseSelector
    epochs: 200
    retrieval_intent: faq

policies:
  - name: TEDPolicy
    max_history: 2
    epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
