language: fr

pipeline:
  - name: "WhitespaceTokenizer"
  - name: "CountVectorsFeaturizer"
  - name: "DIETClassifier"
    entity_recognition: True
    epochs: 300
  - name: ResponseSelector
    epochs: 300
    retrieval_intent: faq
  # - name: FallbackClassifier
  #   threshold: 0.7

policies:
  - name: TEDPolicy
    max_history: 2
    epochs: 100
  - name: MemoizationPolicy
  - name: RulePolicy
