
version: '3'
services:
  deployment-civa-augmented-bot-action-server:
    build: .
    # tag it with the registry of microk8s
    image: laodocker2020/civa-augmented-bot-action-server:0.0.1
    # expose:
    #   - "5055"

