apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: pgadmin
  name: pgadmin
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pgadmin
    spec:
      containers:
      - env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: civa@talan.com
        - name: PGADMIN_DEFAULT_PASSWORD
          value: civa
        - name: PGADMIN_LISTEN_PORT
          value: "80"
        image: dpage/pgadmin4:4.18
        name: pgadmin
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pgadmin
          name: pgadmin-data
      restartPolicy: Always
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-data
status: {}
